/* See LICENSE file for copyright and license details. */
#define BORDERPX        0
#define NF_OPACITY      0.9
#define FONT            "fixed-9"
#define NORMBORDERCOLOR "#cccccc"
#define NORMBUTTONCOLOR "#cccccc"
#define NORMBGCOLOR     "#cccccc"
#define NORMFGCOLOR     "#000000"
#define SELBORDERCOLOR  "#ff9900"
#define SELBUTTONCOLOR  "#ff9900"
#define SELBGCOLOR      "#ff9900"
#define SELFGCOLOR      "#ffffff"
#define ICONPIXMAP      "iconify.xbm"
#define MAXPIXMAP       "max.xbm"
#define CLOSEPIXMAP     "close.xbm"
#define MINWIDTH        12
#define MINHEIGHT       12
#define TITLEHEIGHT     30
#define ROOTRIGHTCLICK  "xterm"
#define ROOTSCROLLDOWN  ""
#define ROOTSCROLLUP    ""
#define DEFMWFACT       0.6
#define DEFNMASTER      1
#define SNAP            5
#define DECORATETILED   1
